### ISSUE TITLE
The select doesn't handle click outside to hide options

### ISSUE THREAD

**Issue by slimovic** [joaoneto/angular-bootstrap-select#12]
At a given time you can notice two select show the dropdown list, normally when you choose another select the other one should hide his options automatically. Something like that:
![issue](https://cloud.githubusercontent.com/assets/8292262/3751360/aa2dd498-17fe-11e4-9386-292c61bc0cd2.png)

**Comment by milenon** [comment]
Hi, 
I may be missing something but it's not working with me. I'm using the latest version 
https://github.com/joaoneto/angular-bootstrap-select/tree/master/src
together with Bootstrap-select v1.6.4 and its css and it is not opening the select. 
What do I miss?
Do you have working demo somewhere?
