### ISSUE TITLE
CSS style not applied

### ISSUE THREAD

**Issue by maeishoj** [joaoneto/angular-bootstrap-select#20]
I have tried to make this work in my angular app but it doesn't.  the instruction don't seem clear either.

I have imported the following:
`<script type="text/javascript" charset="utf-8" src="js/vendor/angular-bootstrap-select.js"></script>
<script type="text/javascript" charset="utf-8" src="js/vendor/bootstrap-select.js"></script>`

as well as the css: `<link href="css/bootstrap-select.min.css" rel="stylesheet" type="text/css" />`

however it still looks like a normal select: 
![image](https://cloud.githubusercontent.com/assets/1631903/4737660/19b6391a-59f7-11e4-8605-b42432c542d1.png)

my html: 

`<div id="navbar-brand-language">
<select ng-init="currentLanguage = currentLanguage || siteLanguages[0]" ng-model="currentLanguage" class="selectpicker" ng-options="lang as lang.language for lang in siteLanguages"></select>
</div>`

Could someone tell me what I am doing wrong / why the select button style isn't applied?

**Comment by nvme978** [comment]
I'm facing the same issue

CSS
    `<link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.css">`
    `<link rel="stylesheet" href="/bower_components/bootstrap-select/bootstrap-select.css">`

JS
    `<script src="/bower_components/jquery/dist/jquery.js"></script>`
    `<script src="/bower_components/bootstrap/dist/js/bootstrap.js"></script>`
    `<script src="/bower_components/bootstrap-select/bootstrap-select.js"></script>`
    `<script src="/bower_components/angular-bootstrap-select/build/angular-bootstrap-select.js"></script>`

MARKUP
    `<select selectpicker ng-model="model">
                        <option value="">Select one</option>
                        <option>Mustard</option>
                        <option>Ketchup</option>
                        <option>Relish</option>
                    </select>`

My select box looks like a normal select as shown by OP. All libraries are of the latest versions.
