### ISSUE TITLE
O que é possível fazer com esta diretiva?

### ISSUE THREAD

**Issue by ThCC** [joaoneto/angular-bootstrap-select#23]
Bom dia João, tudo bem?
Seguinte cara, eu estou precisando fazer um bom uso do bootstrap-select, ao ponto de apresentar opções em uma forma de hierarquia. Usando o "data-content" eu consigo a seguinte apresentação (primeiro select da imagem)

![bs-tentativas](https://cloud.githubusercontent.com/assets/2923857/5086855/5b0034cc-6f08-11e4-98a5-35e82697353c.png)

Porém, o que quero é o segundo select da imagem. A diferença é que elementos que estão no nível 0 da hierarquia (são as raizes) não podem apresentar a imagem do lado. No entanto, estou com problemas com o parse do AngularJS no "data-content". Abaixo segue o template que uso para a minha diretiva:
```
<select class="selectpicker span10" multiple ng-if="config.hierarchy">
        <option ng-repeat="opcao in config.opcoes" ng-style="{'padding-left': opcao.profundidade*15 + 'px'}"
                data-content='<span><i ng-if="opcao.profundidade" class="icone_tpl_select2 profund_{{opcao.profundidade}}"></i> {{opcao.text}}</span>'
                ng-class="{disabled: opcao.locked}" value="{{opcao}}">
            {{opcao.text}}
        </option>
    </select>
```
A sua diretiva dá um melhor suporte para o "data-content"?

**Comment by joaoneto** [comment]
Fala @ThCC,
Desculpa, eu não tive tempo de responder antes. :laughing: 
No momento que você perguntou, a diretiva ainda não tinha suporte porque estava com conflito com a diretiva ngIf, que gera um escopo isolado, se você puder fazer um teste, seria de muita ajuda.
