### ISSUE TITLE
Still have 'Nothing Selected' when trying to use Ng-options

### ISSUE THREAD

**Issue by Findiglay** [joaoneto/angular-bootstrap-select#38]
Can I confirm latest version is 0.1.0-rc2?

Ng-options is not working correctly even when trying to recreate the demo 'colors' example.

**Comment by PersyJack** [comment]
include bootstrap.min.js
if you look at the source you'll see it creates but the toggle option doesn't work. angular-bootstrap-select-extra module supposed to provide toggle option but it doesn't work therefore bootstrap.js is needed.
