### ISSUE TITLE
Significant slow down with a lot of options

### ISSUE THREAD

**Issue by m3Lith** [joaoneto/angular-bootstrap-select#44]
I've noticed the directive slows down the loading of the whole page if there are a lot of options (I have ~200, combined with data-live-search).

**Comment by raafael911** [comment]
+1 I have the same problem. On one page, there are three selectpickers combined with data-live-search. They roughly have 100, 600 and 1200 options. If I use the native dropdowns offered by the browser, the page loads significantly faster.
